# Generated by Django 4.0.5 on 2022-06-30 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('researchers', '0004_seminarandviva_type_alter_researcherpage_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcherpage',
            name='address',
        ),
        migrations.AlterField(
            model_name='researcherpage',
            name='contact_name',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='researcherpage',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
