# Generated by Django 4.0.5 on 2022-07-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0007_rename_contact_name_researcherpage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherpage',
            name='department',
            field=models.CharField(choices=[('Architecture', 'Architecture'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Computer Applications', 'Computer Applications'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Instrumentation and Control Engineering', 'Instrumentation and Control Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Metallurgical and Materials Engineering', 'Metallurgical and Materials Engineering'), ('Physics', 'Physics'), ('Production Engineering', 'Production Engineering'), ('Management Studies', 'Management Studies'), ('Mathematics', 'Mathematics'), ('Energy and Environment', 'Energy and Environment'), ('CECASE', 'CECASE')], default='Professor', max_length=225),
        ),
        migrations.AlterField(
            model_name='seminarandviva',
            name='department',
            field=models.CharField(choices=[('Architecture', 'Architecture'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemistry', 'Chemistry'), ('Computer Applications', 'Computer Applications'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Instrumentation and Control Engineering', 'Instrumentation and Control Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Metallurgical and Materials Engineering', 'Metallurgical and Materials Engineering'), ('Physics', 'Physics'), ('Production Engineering', 'Production Engineering'), ('Management Studies', 'Management Studies'), ('Mathematics', 'Mathematics'), ('Energy and Environment', 'Energy and Environment'), ('CECASE', 'CECASE')], default='', max_length=225),
        ),
    ]
