# Generated by Django 4.0.5 on 2022-08-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0008_alter_researcherpage_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcherpage',
            old_name='facebook_link',
            new_name='orcid_link',
        ),
    ]
