# Generated by Django 4.0.5 on 2022-09-14 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0009_rename_facebook_link_researcherpage_orcid_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherpage',
            name='date_of_joining',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
