# Generated by Django 4.0.5 on 2022-09-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0010_researcherpage_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherpage',
            name='orcid_link',
            field=models.URLField(blank=True, default=None, help_text='Link to ORCID profile', max_length=225, null=True),
        ),
    ]
