# Generated by Django 4.0.5 on 2022-08-31 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_remove_eventspage_events_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='details',
        ),
    ]
