# Generated by Django 4.0.5 on 2022-06-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0002_seminarandviva'),
        ('team', '0002_people_profile_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='profile_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='researchers.researcherpage'),
        ),
    ]
