# Generated by Django 4.0.5 on 2022-06-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0003_alter_people_profile_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="people",
            name="email",
        ),
        migrations.RemoveField(
            model_name="people",
            name="facebook_link",
        ),
        migrations.RemoveField(
            model_name="people",
            name="google_scholar_link",
        ),
        migrations.RemoveField(
            model_name="people",
            name="image",
        ),
        migrations.RemoveField(
            model_name="people",
            name="linkedin_link",
        ),
        migrations.RemoveField(
            model_name="people",
            name="name",
        ),
        migrations.RemoveField(
            model_name="people",
            name="phone_number",
        ),
    ]
