# Generated by Django 4.0.5 on 2022-06-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='thank_you_text',
        ),
    ]
