# Generated by Django 4.0.5 on 2022-07-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contactpage_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='maps_image',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='latitute',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
