# Generated by Django 4.0.5 on 2022-07-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contactpage_maps_image_contactpage_latitute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpage',
            old_name='latitute',
            new_name='latitude',
        ),
    ]
