# Generated by Django 4.0.5 on 2022-07-01 19:10

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='side_heading',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='side_text',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
