# Generated by Django 4.0.5 on 2022-08-31 03:54

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_side_heading_homepage_side_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='side_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
