name: Deploy to production

on:
  push:
    branches:
      - "prod"

jobs:
    
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: delta.nitt.edu
        port: 22
        username: dhanusht
        password: ${{ secrets.SSH_KEY }}
        script: |
          cd rsf
          git branch -a
          git checkout .
          git pull --rebase origin prod
          echo "${{ secrets.SSH_KEY }}" | sudo rm -rf db/
          docker-compose down
          docker-compose up --build -d
